apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-ingestor-spill-vaio
  namespace: database
  labels:
    app: db-ingestor
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
