apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-ingestor-spill
  namespace: database
  labels:
    app: db-ingestor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi