apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
  namespace: database
  labels:
    app: ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      nodeSelector:
        kubernetes.io/hostname: vaio-server
      containers:
      - name: ingestor
        image: mhmdzawi/pi-mix-ingestor:ead73fefbc32b76d9ac39275b26b616b841fa351
        imagePullPolicy: IfNotPresent
        env:
        - name: MQTT_BROKER
          value: tcp://mosquitto.iot.svc.cluster.local:1883
        - name: MQTT_TOPIC
          value: pi/dht11,pi/ldr,pi/scale
        - name: PG_HOST
          value: postgres.database.svc.cluster.local
        - name: PG_PORT
          value: '5432'
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: pi-mix-pg
              key: POSTGRES_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-mix-pg
              key: POSTGRES_PASSWORD
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: pi-mix-pg
              key: POSTGRES_DB
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: password
        - name: REDIS_ADDR
          value: redis.database.svc.cluster.local:6379
        - name: REDIS_RAW_HOURS
          value: '6'
        - name: REDIS_15M_DAYS
          value: '30'
        - name: REDIS_1H_DAYS
          value: '90'
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: pi-mix-redis
              key: username
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-mix-redis
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 8090
          name: http
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8090
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8090
          timeoutSeconds: 3
          periodSeconds: 20
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
  strategy:
    type: Recreate
