---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-mqtt
  namespace: database
spec:
  encryptedData:
    password: AgA5WgublLCDvEQt0oxMzwdjYF9z9MThq25lKBJnIdntD0RGdMBNPWwhn8OShy3DKcZvlm618nLk++TffUgklJ7TmUHuBLq/UrQTXH0oHciymB+CeVxbjwwZyf+FQr6p+5vHT20dyaVWsHtH9e1YWf5hS+oc0t3raA91irEnK87Ru2VTKM74eR70S0yB151JbZBm61fq9DSUAAlmyQnDO87t93onvB/d1VOLelbAlAs4xoxBZWwBGnDYK2/PCvDkCNM/t24EO/W/RDCJh4UQ2yxLnve+1pI0OrnrkT/WzSxiwgSZtEp8Jdj+wR59jdQ+dbkdWz8jdEp3wWjCRhNtyVNrbee78X0k67C9jQjar8aVjYm6eYxNyY07wqe3HrWW57qGSACreKj7ATi4zJiBDmkcFvukKLv1biYzYMQnUPRKaU+lEA/3Inl2r3sMy0MFps49LXK4XZj/ISdpxm7TETiIJuA+Sou4exdv3MHLeXY1x1TxzvYvtYMV/tRqmoVvAOP684ws0f0cUmyWqSS1gFsAQJszrPPreH7UPqzhcg2GBZS2odpv22cu7fdndLaa8DB6EO8MmqA4timH8C3HvzfHnEXac5lxEraHF0xSeB+ja7b2wJGFwJlgSPs/lwOQxnfMd+eWoL5b41zvTmu9rVTRGIkE0pTTpIHqxVsspeSDmxqsQZCzI1FL4aRsyLaNnUBymB0HmZk3n5eVA2dmRvctJkpGyxaYcRtM3bmZF2DUfriUO38aQ5BbVzDB1MxW7xbL+tbfTUzB4OuBlb9JF6rp
    username: AgBHfTxFTSc9bUhjt3q7lCRfxaGsOlaPFjxK1N/VnJ2nkNAr/g5geFew5Q1VkXEPuavFycLZD2C9i7Cq8DSJQM6VXF6ZOjM+VIxmxZDHJOCBFo2tcUEVuFRsYy9nV0BW6Y3j56R1EYYwWZ7nhfXhEaxfizUkis6+Y+flUn2UW+lV5v748iYEyI77MoZutMJI7RrFMpeVSDfc7RDL3k1cC8zoiC/pi632miGto10SjW3wloH2ra9SBgnrjN5o01Uj+VzdBQRMmWmlVfshwNJqAQWA7Aw55Jn4QCTIx2QLJ4KDa5lCDNHEhXXl3Kmc33UHs3AhN/C2cd6IliHO0TCX1Tb1r8ozcXiGTkYhQAAPyOIxAD8C2Qgjv7zi++yX7doShdMnOUJmYxKVeMKu6LbAPogLAbNrzG3+oGnblHArjWJkEM3bId8jX4na/XANfSpZhEnXbdVYa5IlEddkBWQOWZS24aw9WPiIE/GdU0oLHX3h6Whwph+vFMHdqjnK9aCH+xeupMgBPn4PKPMJMZlkPwfSf/CQ17aT7FvUZQDpzBiHgKp2XcGCf8y/erF09MOApm4omk5YaXBhppMb1dHlrc3jwKIcAmPOgEubNThcYtqWlHZcGeNeMPZ9WzP/x3XSoE+wHIa0oXO9jW0xCKBv+tFqE6iZ1zOhxLBUT93qgj6xU8KK80PmMdm+j8pRE+qDv2RRaFztbzw=
  template:
    metadata:
      name: pi-mix-mqtt
      namespace: database
    type: Opaque
