---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-mqtt
  namespace: database
spec:
  encryptedData:
    password: AgArRergOAlvwR56j/NF0wi+5BmMce6jlMCY4Fh6F1AD34++6S6M0C3e8kDl8S+WGyQCrAJvOz/Py0LwxTVrq7EZ1FG9lMdjUY68Iyx3/LXP9bNZXXjwoDZ1isYoNkjJIDgrFP3/hGvpR0+V+UMI3ikttXeuvc5+5IwpMyYvzjr7FLX2dLpLXN53hULZ7QIdw8uGxd2W3owW5UVX9cccW5BCRd2FiO2S4D7ZuDLoExFOv1tMCflnQO/3crqGF3RWg0uly3u4qe1WkEcwMC4UV1TaCZ1i07SCYSaq6V++wr8u5YYlWvpIlnnqZh0RkpBiDheTsgXAQOkfZmonOrMI25Wgqag2hPA6xOI24ESejngmDXr4YJuXHbehgZvVuO4ZzlubGcMnenGQDL1G3ACHk9sMGQVsQjB3D8w75h9Kpdk77IY19Dk2nOz51Vf8DpneV1TfYUHVjUnWClPnTleTfRsekmyibqERsVyV4gmY6paGrn+QFpvpPK2TM1DTEy/KJt9DblyG0JSCN2QESMFtGuzX8kI35fQRk40jt9jUM2ThAFyHxoBqJnQ3WlWW2RlF1AH6BHa86scwrjP29CbrMGQzYqGHszaNVuU0In9LjlE9GuEdVO9Puei+0HhTwkfzyoC24/xLDAxTlxQar6awRbDeHcfdWFh6s2+WssZdD4g2zXHYBnQFIH3o/ICZXDsBzzxerhwFsI1OqrBPu0RhoK5fY6DpwEz91aE0PTqU95iCw27dHFItPDtur/sLID/xao+MtNE+cxX9exh3irV5rIZI
    username: AgAVnYrUVXeePhx4lbV65aP0lSQ9kfYNc2/92BS9B7mhV8TocquSNs5V8eZkH9yyHCLI53PVlEImMjY+BeqJsWh5I9izKUfP4ueNNh7YSe1AYI+8ztsO8sMVlgdQqqsOo+tL+OXVRfI3+0eb6kjsUD19fB0vEwlGV72vgN+4mIbSmFxgRl+wgvwBVu7IWNNRlikS1ABn48UU6Ik6iQYbpGYj0o2k+T99TSjlyZCQV4eDrqxL2l1ntpwJBcz6zel+w9Mvly/KPBxnuo2dkLxw8jGw9vCaJxEhh/V+G5FRMWqwKv+sbqERgJt5qquw0/yi3uDAVtUvADEyP9OmVcdGfZawwf99xjO0Xo9yB7UslwMbKAFT0IwQJZxn0N+xHJffxB5qxO74krvasUtJ4ClR6sbmSTqdGm1cGft95SvYdF6hj8s33yIHL+1JK0mt9oA3FNPKeYXU7z7l6EVvpVhTJmnI+5Jtw0EQS1aBnSz+I3m3ddhWuX0G+rnBqawsBCCKPRgk36C1tcTHCFiY4mvRQt4AE2ctn06WHAln3jB/fTL+gtRjd8rKIgsf22CalsXyfqUeyOaJaPJe2U9VXAe9JZifmOZ//dioYMpKfe3A5SGVlwcqOmn0SocjwynrkbepS7c8zeugB+M+RBcpRCTBL6X/jgeW/s4yPG4HULeFKYBuAQClrN4ys6m/kNq3AF36ShQCfnwPsYg=
  template:
    metadata:
      name: pi-mix-mqtt
      namespace: database
    type: Opaque
