---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-mqtt
  namespace: database
spec:
  encryptedData:
    password: AgAZIJmkJoKI5HyIksc8KFbpi1hiscq5h64WqVP/7mt5XPrT1hF1QYIVtriLmgkcFCt2L7QLKEBV5RFLL/uKlxouwx0JCGRwLwi/LjzFbuDdUcDKzmhJLf8dOlShbzDfBKipb+jUbUyvw/NaGndbIav/D8r9ui7HtJydzuLYPiP5hgsZv7Ex7KSBnNCVyAAmbz1aDpYbZvl7DQeixQiosj6YjmFuM0bqpyEUKzYA5UPFUNkD+gTjtatkxkFhzgmj3Ak8Aq21l6xZsjYvAwCK49Nr7o2qPEZiB3Y8om+edE7Q+uTe0i1grx56knYoc2qNS+jysYXs0/T3aN90CZaOL3cidne2Xbq6+cGBWTBbTWtNjpkQPDizVKq1wuPD8bt/hx2cgxOFH4pfEB21ZapSD2dAJ2XHAQCeSvG6dfR3G2ed/Kzax2DPd6Noi3WxqrYjcPYE5hMLxEpu6RbPlULU0j58D5sLR9A54NF+pR/Sd52J8oMuZhZbLLRiweEGG2Fc5Ul6z81qreUDDzEoUnXI6hIwn/Q5qPNdmhefS0AZ6uQ/MpH3HJAXtne9C942+Cgw6H1b5uZJaS5cqWTzAQmHd+6VTZRfwIkecBs5j3y8D/VOwkY3ECblJaiG7hfZKzaTWE1bja/+47YnHZ8E1QOfmeGrmYHqCwdAZI8uAkbBgch6J2jeyfnfDqzdBhmOo932zb9zPP85Ly5Xag8CzLrAzA2Yuzkqmn33nToQ+CSNGihZZfV5NnmA2HLRnF4SZr8HpMZWf+1EzHwYQwy8wL3kCUmv
    username: AgCpQ+JhGx+28IOozsnD8m9A9xX5wEk7AgxqKTBNbNMJgfVmYBFAJNsTg8qmllnZs86n066TTzeiSQRzJkxLrLYKapaNh8eeKVYg0+09mMoztJvHdcrPo1ofKIe4ji4zC6syMBbzyZfPzPCvhd913LcL7c0FeEgVeaztMuKQHn1MyrCMI7S5rCGKTVinjGcajSn+KZzaaIXIw1x58S/fGnZ0hVReLAOG3RqaZiY6/vXnMpl4Rghz4iVM9LB0ji0s72I/uu+9eQyRByAMd4V1LOztDqUtT6m8af8iNvlZAdSO4vMBNGrEnVSJDA1TB1mQOuvXhW6e9Xw0wjzYg8L3FhMJjnWEd42PGcH3zIU5UxgllwObUmoT7d44uoRaOEQYE0dvz5iFdGsAbsTASHfy2US0GnF3XKnIUqU8a5m455Moh0BLQ0ArKxmITAckxbtMifRuNPp2acxj6KFb3ocqXy9QQWfypwt8kccnl0GE5c8cRDnAJB783pHVf8Zqd75GgHaXmPJvQqbY427TCEjJJeGsXeo3/H8My7UI6JZrhFxtODA0019jXH2Dx1vLn5RX86S5IBBDtSEuVvGfI4mvOM9558IgVoyZuR8GYyNsyj3qvN4ii7ar4lxBWBh/ba52rodYOqMVMB5wTm3bJ+omxzbt3ri0CNDkuDDSsO8+Eb1qzmedmIgkst9xbXx0IACIczIGaBLNhCc=
  template:
    metadata:
      name: pi-mix-mqtt
      namespace: database
    type: Opaque
