---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-redis
  namespace: database
spec:
  encryptedData:
    password: AgCY4kWPCrXnfxpmk0uW7+Y8fDteBQdXNz02P6XP4EBpA2ITzw4ExxNykA5nNxYGh963Sd1r0ej5E62bGB7H5r0oEl4ikmTt4YigXL+1mLux+ACEPBQhGw6BOO1piTIS4p58Y2PrOoElyd5wvU7F1UNZUTSWrBTanhIuIXJQ7mdx1a4xBBbgez/jLttaqIPhuQTCNnBUtkfYv4BTfISXMSjaTRV8r+gOHYlifgBtxApwiLBWo8B9G6heplYbk+OWdF6hFFXAevs9pJiTyYwbsfPATJTsbwEMi3lIdJ9mtYpuxUbL8jMqEtmBj+nc5Qg20IXRjJ+b4wOWxnGqL9Bm+iMnxzvVxx9CJDSkDpYf7QgPc7TaezzH66vvQdZewyBzHtg2hprpcQd2okCJYXNUFAVtSisSCMR8mKQW2pKqu3/Icc5I+mLUTE5FszKH14vDd29mlmllbIRaOMIHowKwefOgD3vlMwT0NI4OVGpJKm9mer8Xcrc4/AHUbgDjefOSxcRf/7zRWpjBgtiOMPr2sMMSRqrsRTIKsPHL8BVclmSfYtLeHS7eJqCK1nI9lrSh3Fn5bGjQzvhHwK6NPnEuRWkXBXUDHN6j7f336vi8s+eNR4AJrTgdms4XtwQznA6OAzXGDuob+R7ZjRHB3ZQRE1tow8M9xlmQXHkaYSccDGP7YwvnmbH63OPfDiBX5YV93HJUJclSeXCVYWX7Wu4Yo/H83VvPvv7eixxwEo1mLWZiOkC6iTH60LUlZTVTpB4xDBQty800miFl6FBVUrd6AF0u
    username: AgB0afNf1982FK/QegIS6OlrfrK0UQi+8k5YPeJ8oVX7Rif3KwHI+QL2+pa4ReuE7f82hohvfLF9Ph3SLakgQr9BKhCmvQOQZIbJSjxmI6i3c6Igl9mxIcpZyDpBZVDGM5fKeKchdnAc08jQHLWvHr7U3mobg/FA5VlesyiltM0rhcFFwR/pzigcSXVonsCEMio1rG+vfCpjncW0NfS0coGAon+bDdyOKv+xuMiEUZJVFe3+/jvaIq9qMuVP13rFNrCfKYxhtNLRqHc3TERqxWIZ9b1g9Ae1zTruSo3pkLq2mL/KHZt283Qmo55A0VElMOcKh/+FFIg1CfKQZZMht1mv+M9pogI3lHRHiKZTGkVFjmB+cDvw5TsHsQFnKW8O/Ewm5+Md5906Jqotk+0nCxNBijmwEGMdipowm2nDKHZ2yqKa6qaVWOfMNdN3wQFl1VMt1luOWnqxhSEX47OL/PloC9dJRGWjDDcdLQljijo4VAQSyj+pDWB4N/+mSUGkt94CmSX0Lnxt+AMs0Fuqr23I39r3Em00fupEonhbPYbcE8OEjapmDrGo30cPbznxKiInNZ2qUVpl2N4vNY4y+Tewp01i8aVZiNdz49H18dccCEyMJjCNnUMiT7qfCBV9keSQGZ9OUxN6ahHzKx9qIzICJmKLIjwyLKlQNaorr1rpbvbSq1zBBV3ctpwj5iLifcIcwnhY1/w=
  template:
    metadata:
      name: pi-mix-redis
      namespace: database
