---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-acl
  namespace: database
spec:
  encryptedData:
    users.acl: AgCHyR9qQ4xQ7gRR0ZAavgf5QkBjH2HQZBVdI89HUHpgf78tfSuGLUyJ9fWDXnFmMB58yVQ1QRmBI0mXY8pLtGA6QMpFJpfujm/3qiEVne/r9xtEPlwemP4DRmerNCR+5W18/fPC3Yx2qlXhoIdiZf2uFGaV6uUjfiuWa1fLQiurO15W4pmhN3NzRrqgf6BdLI8GdHrSJJy9eW5OAG0Nc34hOKFjbt4R29QpkyoKCIOf2T3CPLuEct/3gs3rdjynMqfLDZgDmssi+ABsZf4NLFzt+N9f+dgqD2Tay3hk6+LwaIMTyMXSkSEBwDmJT20EZYH98GEl4chPJmDfH/0whGkEX5J6ZmBkc+QojzBkCZU6AvficVzDpU0PMU8lwltu0him51/JHLuK7vkvGYINpG7kw6osCj9rJdcuWPDypg2p7p0dEloRnjnUFPRb7I/24hBaOjkEqRgMAekKHg5Z6nu3+KerI2YJ5sZlJaBoMrQUyMrvpp4u/vfk+FoVqKUA6xdJNrcJworUdYlPD4vKNVc3vmuXRIra8yrOTlEltu6+h/vNxvCTzdqKb19uxW9kHOI/ias1r4wvbnZhZFLmU4KjdOCLhAJkOccTLSwGs2lz/Z8Ruj8V3dbCvyFmmBIa1LCjrHQmdpQ+2ufLGvOjIhVmYn0bofFZirBTvSfnXP3BuJbtaLk/9QvAEcPLl7skdiwHwnCLma6AKVHLTAfOeZ2Va9Dvo/pjO8O8BLjI1lgDL6lHZndU4Rsv1TMXEUdf07O9anecrd7GxF48Y0MS21Bqldgixs2tq53bDjtlSsPLTN3U9uekONVQwwrUgD4lMLy7wv9z6okIJnZ9W4tO5p0RqlQi+EGtNMt3e4XATeN3sJV5+TYE4Jbl3Wj+4geq+rhl6BoQQ8cJJaPlZxnR8dM+kJWR3P7IniOBoRQQFHvr3dP6ddMCrQoIRU4sR2laT/gMdAEDlay1xzyujlhN2o68RIipaP4vGCdY7BlIgJ/aCbSGnTqx1he09BS8w0J4xgVGDRfbpejXJlFOxndl2aN0AfCFnrVh1geBZ8vu61PBiUt56YFJTblmIEbN9r5nLQbXT8yHc3uDMUlYrYGcWoIDiCFz+2LoLjefUhUdcZDV2HorWSh7FJN0qQH/XnYJwog=
  template:
    metadata:
      name: redis-acl
      namespace: database
    type: Opaque
