---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-admin
  namespace: database
spec:
  encryptedData:
    password: AgAIMtIIEBtnNLX40i67ShrK4bKyORAmf4f0kH17dskcJkCfyPDIelNBXunHGXJ5TFS0vsxmAaMOi+ui3uyNlxBDDyii6dmXwEVox3lYm8ZETDfWBx1nIsvu0iM9Hkm3Vgu+1pkPVzY/7ZKTOIZOsfyxdLSUD/8CIztWFKVzweTEgIAtjuytpRemnFwxO1PHxugV2UuAKNQCANt4GubZGKtQRT2J8EUGZCL6Cj1sRSqYEGqNmhVGnUbEmCCnIdckYxNFrPOduBOIGpL/ZnKoazvJtNpfX9VrJAurodK89Papjm1RgvzYmfIuCZlOZkC6aPAkGWlrlY0eQwWlu/3KSHBmxYcGb5VwFYnXrelfuFyiDSRsTLdhlxyRaH1UE1AKS+CZsOMXqe0xKVmWXA5C/6uQOLTeD7h0JZ0Ye7snIOXQacu4pOkczTlmi0JyforR3Wgz57xWBIXepjS0q2M0wVNngA38kcUVWJGnKbW1oj0ylCm0A5dtty65NfMWq+j7xVJugdQn5pAmO8Ch8mPpXc5B8vvEyOHvBMhPi5df9JSj3t9carcI7L3Q9aJyzLVtlLd0yoaE652WfFTAmnQIi7OqwTbjri8ewvm/4MPwMi5edFuoaehl74LuWkmCUZO6MjrFm0kNNiRiA7MViIBndyl8+a6PbFn6XzBOidO8+93W+OKXq2LnXOayAKRfi2IIWMTzfqNgfFKP0wXhfyPPE63h9W8kyxjxV2d4/SK0uFnugpj8k6VB1CvsPYzGoWC6A8CfXUEg6wGLhWoqJiI0gTen
    username: AgB2A2zlhVpsEHryBAP7CKR1YhReXgsmbd0qrPfXKdgjjqxQC08uIUWeyHY3JAPxj8LTseeBMHucN4sy1rXBCAeo5quqlUqx7MejyvHredBjxxlyI456oTsWqZO4BhPRhhloHH2welyymKepX01f8Le7I1SvCn1CFUWMCxaZimA7ddOmUKCQC05FGlB2fP6Avnxt14eFFsZmtiEYvLEoT8ji4rls+nds6uFSX3eA9WTcSFDRRqWTbhN8Ds6GKyey0YWbT6CfPwk+3KDP9fXBWkPqNSjmRnmjcp8G2HwKns6etCFYB+03moQAA0N6DDNg0DZZyqqTqHxq1nF5GupFMLYC+0X16rkHwW4ag8auFe8zUx89I+zs6rxFOnkeYdV6uZEmf88cQ5pPwXlVAtBAlj8QnD09HQNu3ihRfbOqj9Us/xW5JdydgyYrIVLTHJMT7nbpw4PywqM3iB/NIVjpUuIOZqm0UF9WvaQHMZV471h+brBO2Km3SyC0Wpfe4px49gKLR9ZS6bM8ChHW0fM/rNZidH9K/8nOkoGs6r2nzlmfQVyd3IS1/8cWNiFdRJ24ytFlXRrdD5H6IYP4oYAeZEv4wX32WCPf8tKEiEq7OD5EPk2+6MvX6N6wokQeJbhi0cxNNDQ34j2B3/xowk+Ahji1lX7B81lkW22cCU8Hs5AqED9F4wYd1NQHsFvTCAtHwxiSXTuCKA==
  template:
    metadata:
      name: redis-admin
      namespace: database
    type: Opaque
