---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-admin
  namespace: database
spec:
  encryptedData:
    password: AgCKFqOHCh17RFUvrKyw3d3itfcZ5wh+8V/Dc0TnRvNkVn4heC20HJSP3nAy6lzHl7Y6D6nwgx6uCUyHk9Ihv+nk3b3f0X00CvMlVKZeiZdNZXgKCFnbRzIEgDZP7hcaZFM0mDQRV1f8Pled7QR77XKkVmaUrsEEd8V3D5p3WegC3njPrZa+MFlivvyFW2qklSrmfWyGz4th2lfgzZ0fwodvXn6e8dMvYePqD6CXi+9LooWDje9Wiz9SWhu7YV8pDK/lvz6VAjYUfa+upwKKvE2rP2CBAIAFp+x2qrT/oe/7HFqLDrZ6YkQ9CWktTSAEbg3uJD8CF3Blvf/8HVd2nstj4j2LrA4H/CLvmsAJObmvFsrLXLGf2QD5YkCci6ytBrpoqxauFUoixWjqnfCZUwssoqUFU/StX1OQ+JAft9OU28hOlIX1/FsofeOdBvCxVXlL5wa4N9Qn+5nUC6pv5klhEy+fQWxL3bPVCogJ2LeUnBMV67nJaVVft3OCJEZq+px1vAEyOdFBu48Mpwnz6N2WcCQnLIR/OtSmSrgxleuAxzIZOzIh40Uc0r2RhnXoWdHVsHmQQaozDiPvNXapUx3ffjWqFvItVuZVoqpakedf97D4GgCb8y5C5MXvra/glG3TO5ASeZSUxWv5M6+OoQHXS8XsI6NAg7Tw7ikHVLmQzkkejHG0Un9yPggaqH8vDMZLoYjhRboOC3tVXAryCx4+LEIW4rUAWpdLe3ZMCu398lldO1tIKJXlkXdtLkfQUTS9Eqqol/Hu0NocRtm9fd06
    username: AgBTNz1UrucFXBNxHp6BPgH8VJ6iAmrkdzjfhHr8WP7wv26I0jtTH0UYONuul/R9mmcgjzDUWyvh/oK2w5iynE3i4O4RFdzhomgUrkQv794zQBBYMb/LHIzbmO5p3GC5g0zm3yE5uAd/UgYo275iHZp3dI1n9nQsBwkBf0pE/8DTswpPRLFGIYa4qpAa9fcZEJ0TpT9qFUUHebL62l9i1Ci8p5AZWMvk0CgFnQYBTPx1IiKI9aF5gDe+rMXh+kK61Kguz9+X/7o3WiHgUCBmLV/0/0Z2gGvRGjivgxqDGXhXm7rphtsavCGWLApLt+0zP1xryVwSdbRmhBMrju5wjpsa2vRtHe0Zs2uP2qu/GvtwtLETEY1G3oh/TxL29vpcDYWZD4WhRoLNrolbbRVxqU1ZmXZHTHLtsPnww3HJvbc/zqoofcZ1qwwLVr5ESxWTRCvFU3ZJyH4NtsKilqKgJU3zcCtife7eYaXHAToia4rAXcCVjIZenmFl2FcqqLfWzuRxyvq5rU10w8FTdAsASu3zD1QjRxZLerCsf+KT+1yr4GoVtrJFhk8zOKuY7DWNwLuuWaSV1aZpz+t1mrJSL01CyLF2g69xrb5bS0KIThCSWM0VTEEPjD5aFT2s4BrKcZ1t4mclctKWOHL/5jTVCWWWyb1Utra2Je0hF2naSAur0QOWvipTBLUtQX1JAldf6140sjHjqg==
  template:
    metadata:
      name: redis-admin
      namespace: database
    type: Opaque
