---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-acl
  namespace: database
spec:
  encryptedData:
    users.acl: AgBgaI2SrCHxnoGvZnhih6ROtzwmyN3pUclGBuR73nvEyxi8zaRAATZNtMuNfo0HbHjeJhdoKbS8y0M2OTLjMmU9SY1OEn9C7nAVbO0NwldShMhtozhP5VSrYUI8VxEAnvoXBHukY7kq8XvAoU7n7j29WWmXwRADbjQICGp6Z0b4IRKGao7Ccnosotu+3WwxKibyrePf9zclp+wR/GIY4EILKH2xOcezYNfRzT2IK7r2uwHwiQmzKUsF9YXPFjps4roK4z0VfKUz5A55omNIblaE/cLExuPDvcWFv0WykfL6NjKzwaaZ6OYvf6NH6LFzwVx+R5uHEhpMQTPjXNu3jLVGkwJk04akvwQOtylSoHZQyBVm+h/hfERRTf7FGZznXRE8CA+cyiXYSCyq2A2xF0frKvaQFmL1t/TyNR7owHpBIHmaPgu5nWm/cZsC8PZtnP0Lg6j4Cc+C/VQRbDwcKOLPxABtZTJF0eq9XLNgO19CNbwksA0K1knRD3aYw8Bz+a72XXppy9h7mL6E8MNVgwUNIAjcraO69ydf+2W8dmPOF1EPzIaLxiOBJP9FomWlUpCGJ8JezHxxE40eWsMaBEFoH72B7DRsaLX7FR/kjfZCp0eFEg8Tpo4ExoAe0vJ0PCByj568g5pCTX4/T4pR6uDFcaOxDBHFO3x2sssVh4BUN5XkhSxq442bcLBUU59Xm8cWG7gRfafnXNDfgrCU+cPXGojtH5EoZpZR0aAAcg4lpRBD/H+Zusf17gOo09/T8CVScDhTwg2+mH4Xq4AfpiX9fNai/An/qCwu7xtjTjZuyMgUDgIn8DOIXLAboz8lsvxHdjjHAt6jJwnxe6jBaj3D5bZlN9vg6ELkMJEys0nlt67OjDhGqeja8jQOMPxPP/iuuwcw0IYtyab/n4tssbQK+5EsLKn741v8DdPEqs7G1FKvoAZ1m8m0nUrkKnMRuwFPES8Q85nthSdP35QSPsATAeGVTUePlnqtXibz1n6/Hgak5KBgD68mSViSY38Uqbrc8PPrEamBUEeW6esSCa9A/lr4Q7fzL0BAEP3xUDdAee46By2wa4wGV8DlDm8EoWB8iJuh4K/bsNDx/hFdGkgPRtAvT04Ze1C75RiZ4xCtnr7uMGh23ww+vJY=
  template:
    metadata:
      name: redis-acl
      namespace: database
    type: Opaque
