---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-admin
  namespace: database
spec:
  encryptedData:
    password: AgBKOGNYIOl/x82a6Lnh83L4mu5JYDyWBkJNYtQ1pa5NOqU9SZAe1HP2hycxI+XrtoeWS5HgRZouiP5lNR7DzCU8amzWJm0Uv+VUAfOELuWLBtjW1JDnm+3+TvIOoUYt2m8vRGpcQ2A/4H4TYJloGNShEFkHTSD4G/ILl+LB3qvGRruKmzNQBs0tlmIxNFOqLaDRSBPX8av2Bsk3EKYbXYjnMaQ8sx809/eGl3OqR86iqnvzvDeBWatsNRkv3X2P7xpZSHZVku+qwafuqiHa+aXU/eOdJmgN0EGb4L8XigfROilKLatgLfAEycvB5m7OCmknd0SuKR8DGkxnRGKTfQJREciaMy2NFmdFS88NRnRw+RcFfbk9XHc+nVnUGvBAGbvAjNQ54MXNa9q5v6iTdctEspqgnSie4DaT4m29TABAdvqqnoFM3BOf/IQMJtcMRyarm/vPMxd30sCup9lZapAZnKjULqp67MiBzoHkPZ/DZ2gGmiixM93uEcMaLv7Si9NxpuUrY27IosWg11e6BDB7ccSnMyOJwuzhm8MTEudJi7Vt4Hbi8AqSDayWey+tq1fZjcmkIQBAmWQ1xTIYisQ/KxdQAxcPBqLP2BJjjXMsi+TFJkZaWyub74uneQ8f+E9qlaqC5/trmTgR3Q6jJiBi5dwgHsf/ueId8Z/R/gl9ShbIefq/7zM0H3UqKDTGQw+RkAY0rrN+p0cXkG3oydkm4Nj2n/tMfXRskwRsIEXpTTQHwHIZKsR395DM6+mpmitGLKh3Kgsy6cOQcHRZyYvr
    username: AgB01Ws6KoOyUSzr7naVmK1bFZMxBvlhQKN1jLLHZi1PgQi4OQZ6kw6urun0r/lHqWOzxvL/sxwBwJsQNrRDZaEIiyEm1vkMAH5qPKUpoulVpTy3i3VSucRu5hHhj1R0VtFavjqHIOdiaPJHvTYFL6CkME/9SfDxivDiyMmn4duoLZP9DT3f02hDL2uVmJqpUQMbe2RKWQcpqCU0BftM3t3CRD2sHiwHGlPFUcK01SjmuUsPlFbIVPgCf6mRfynWjf/496JW3vUptE7hfRh3sAs3UlKRzNimDn32FWlWkM1CvNNInRZ6zScPY/rPNNoScNnmxFA8i1ZfhdlySevnFxfymdb/39G22TCa6JUPHRS55Iy+bMWE/4HU9NKrf30U7W1vjubS8IB1qKDpgekUEdOJh2UmtwQfzZ4S0Nu8UXOWO0m3qdl8C4Ylg93kPibMNTv4+GVN3BdgG39tZ2gOOcHYkeH7QdzOTFl8bnEfclIMM7oE1TUqjdWU32XDQ8ZelcUvRfGRwZUjXvGtESGlgMDYbyi3ksH9fjI3+KN7uPN7vNTD87gnNWLHTaetZYccfPV6IYxRWy77j9I08CQ62cAM11a4b9xuu3nS//B+43Jz1SdjjM255c8UGvUrQiLjtEwj8YKYq3i7XMWDV+AbRboIBJgwpoaVxCkEJxT0KSKaKcxC7+kR33vWhwiCwoa2JyYos2jnUA==
  template:
    metadata:
      name: redis-admin
      namespace: database
    type: Opaque
