---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bridge-control
  namespace: iot
spec:
  encryptedData:
    token: AgCDIG7cQjz+P8gPb4OJr2LlqGykGk5Nx+WTP40SE3p33FqrtNcVwGkK0d8HdeKHBQGPHYdA/EWRo8RiGO6OIvG0S3FtkDtTFS3IZ74xS9sHkLQr+N/8YVx96CsBI4ILZ5aoE988TdcroeMsIWKNXIgn3WZAbc8LSIt+/lq9xrzWtoHPkjtovK79Sn8U9kZWK2wy3i/Q4TITXMjFFodPIEwDCv7Np3qya6ncOMvaykAE/pgg8Hr18piKIfccMWlplsFvBwsDpscUa1i9+HioEx6KrNhF9X9/Yr2TfskG4ZgD2QkLyIK9MfzZv0NkRPBDvBGYq0kW9rZhOmFbWS3QrQCLnBeW48gK1XtKwyw+3feRJarJG/y+hnwW5RBjR+BO/fxWjqHbaFPLDVDzSx+G17ZTwScflgDdQJMGuyB0dulLeeS4u8MhK9O49YehgNtI8vYzBJ803yPV6MkKwpI4u5Ot+FqK/7URFOk4ZCDxpuWthBJ2FTUOYNdgL/Qds5g/V8f9EI3+kgUEt9s5tsAfreQ8KF2iDQzxZeDugcB/JWGnnZOPlZDPeldR9xX270xKjnfp7HK2j3eb1gj4i/uCJTjeRJDxU8ybSD95DeqhkDJpmDABUCqh6PN1qcw2YIi4KIQ0P8h9ubct7U5vPlpPTLmvmgI/fs8l/XgcbZx7Rmb9or013xMmWWUeFAebifV3G0Uk1GFrs/+auN3DBPDFhnLBUVEemdBieCSc7J/4RCbrjL240U8c71hy5dyHChx7nDOqiapG+hM4k5xeUxQKOOGp
  template:
    metadata:
      name: bridge-control
      namespace: iot
    type: Opaque
