---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bridge-control
  namespace: iot
spec:
  encryptedData:
    token: AgBJw3lwZen9eVgiJvGRqEM7zs/SX1v2dDFTJCVJ9Lih0mgPrXUmPJx+Wzapqpabrkv4FWM9MEcI4rx98akj+4aQhyORND3/u4T5QzIUro1H5VbrTI5ijeuGBajJYHDoVl+eZUHBoBJ2yXv/0QMpU6HTjvb6Lsdpu9+2GcmgYRVsdWm8DUPBOv5ZJBkxGiqbnjw5gTScOoKkbmLKhHihXqdiOp5BmseZuU6WVVBq9evzt91IhUqljREI2nh9T0Z4ki6D5pu8mSFA+/b7rKM7vdMYDwAWBnS+kBRTYYR6VD7CWqDmvcoepjaoZG+sYYgMlWh19Bj/sJkBb5wTiwg8CiMKEliAP4uz26ZvhPS3EsA4TNvi0WHiZv4PtpMKzmWNYUEJs61u+WaO8et4K/iwAIXSFPG+OkmZGrY8VoDRd1aomX83RDjQKniuQ18zPbOAF/sUa8WlTFN8JZxs6RLFlexoXqplF+GXsdN2x1VZLKHJ2n8UXSFA9OZY0PeGxq3a9lKrHROSyBci5BUkGQDgjK9EOy4hy1A82rdPhwYNi1YewmmM0UX4EfLCXbKeKtNvAUhSIxOE+KfJ2aDskOXosrW2DEYNJQjRD5A0zb0RTgHKBqjOLA3qdtCcnt6imWcDrTA2T6H+rYsjo4UZ9Ao0BHM5lWwMb4H0nLKeZ/Np5GdVaYBrHUq43w1lnt3QXUkgKRPBBN/533dJc014QS7DKgkdCW9gBTEuayPxfgHd0X8nnu+mHbEzdfk7qUHZ/QmwTobgx9Uv7jApG1r9zEQJBhCs
  template:
    metadata:
      name: bridge-control
      namespace: iot
    type: Opaque
