apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht11
  namespace: iot
  labels:
    app: dht11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dht11
  template:
    metadata:
      labels:
        app: dht11
    spec:
      containers:
      - name: dht11
        image: mhmdzawi/pi-mix-dht11:413788d8d951fc17d8d30648e4deeccc74ca8864
        imagePullPolicy: IfNotPresent
        env:
        - name: BRIDGE_HOST
          value: serial-bridge
        - name: MQTT_BROKER
          value: mosquitto
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: password
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 128Mi
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: the-bear
  strategy:
    type: Recreate
