apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht11
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dht11
  template:
    metadata:
      labels:
        app: dht11
    spec:
      containers:
        - name: dht11
          image: mhmdzawi/pi-mix-dht11:f87a73db42494499998f404a102ff91bf36074c4
          imagePullPolicy: Always
          env:
            - name: BRIDGE_HOST
              value: serial-bridge
            - name: MQTT_BROKER
              value: mosquitto
