apiVersion: batch/v1
kind: Job
metadata:
  name: firmware-flasher
  namespace: iot
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flasher
          image: mhmdzawi/pi-mix-firmware:08d69a8c15d358900ece02a5e8476f9b0f95d673
