apiVersion: batch/v1
kind: Job
metadata:
  name: firmware-flasher
  namespace: iot
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flasher
          image: mhmdzawi/pi-mix-firmware:latest
