apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldr
  namespace: iot
  labels:
    app: ldr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldr
  template:
    metadata:
      labels:
        app: ldr
    spec:
      containers:
      - name: ldr
        image: mhmdzawi/pi-mix-ldr:ec23b79ea74f460274ea6eacbc3273b765e7c6b8
        imagePullPolicy: IfNotPresent
        env:
        - name: BRIDGE_HOST
          value: serial-bridge
        - name: MQTT_BROKER
          value: mosquitto
        - name: LDR_INTERVAL
          value: '1.0'
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: password
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 128Mi
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: the-bear
  strategy:
    type: Recreate
