---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-mqtt
  namespace: iot
spec:
  encryptedData:
    password: AgB9VLw9ZZmEFjfeBm75Bs1g3iP9vsPbcPOu1y9yjOqNlBAAWXCr/gErTgyW0CKWYC7nWoXzs4fjH0iSxPTfIMH2UZGtBADqPzkKeaz3QwZMnGC/8ccyFBpxDcB/fMXcUMvb4wvvtNKwvtad56mRDg0ie5XyXW1lvpoptMyZorEqrM0uMLco9VibWQTYZ+TxaB7J4Q1BaDMBwEBJ1UQkbrkjtoWqN+Dv2oc+ZgTyM0wSFlb6s2/i8P1GDosOjYKgtrFB5RHmtW4oQVlUuQPgu7vmCyr/GxmBGGoQ4GkIP97GNl+44bidmBGWVfUcKFKzTZh8xq/CK/XQYQryYbSxqLQbrGbseMTlJbslxuFwoUmIAlPSTrj6eKC7ElPuyPzkAHJYH3YxSjXS7DKHMUzT8vmYqDBJavJgj6hEVbDF9UIta83g0/XlzNW45h5oFxVo++hHyry1eYQoi44Z7R9xJKSFp8VhBXxrUotng+0mv5aL/0xmw5Cb9eMoZCspdSpAUKVdsyTsJSSGqILRRfo3zHtO7Uwt+zqKq+n4Lg2mbMAOc9GH55iSrc7LjJmrgOCiZzp1mS8EbYwPqdnbsCGshNFx/QJnzMZqS0FmjwG1zk+Hz3i64KwU6Oc4TvRl3xPO67ROuYZzkwi3tNuhfqIMoLdR8zGM/BZJvaaFc8vZH9AlfiZMndDA3eySGWeGlZdNWoMNdPFv1GBDEdcf0tDnbQErH2uo3BQRpmpwHS4dKRR8XXcVTnRvh133vIOxqvsAouLBBOsVCh3RMkdxBsQhkv1S
    username: AgAq93A8a/Msk+orLbE4+2en95tk0yyL6hD9A24O2+H9//+G2NRilUU3T2YIwLwVFM6Ytoxyc+59auAQe7WCDDJrhPn1kxAuCOhC2X1W/HurIWjMzcT0c/EBr/Zpp+3aQTfJvHT4fXsj2bYdKHziSv71V0xug8sLr+W+BGXs/Mmj8WRAFXjgARmormN7iwfMmWCLWA6HjKKDi7zEkRzGfZJR/uLpOfmtjxv+CTzKJ1Fly/DV5Z0vzuogwnn7p9bF6mH/hAQdLko5OtYD2IjHopqEsuMtFqO0VCcDX37NRUOhvGpnlt7409+mEHhC5KiJ94g8q+/2bV/2pPKu2A6qsxXjWyoDfhCEd1P6GZ6xL+tuduGdLFS0UNvW5OwNPLuo/tvmQJoPP2Dm0SneyiqHrtsO1n1S7F+bGHMpBhjWGSEefArrS312BWmJ2n415ijFwxf/Uhk9jC1WtoxWxt2AQmAaKXzrVU9D2/bkacXe0UjhKTmFO2IQ9QnQLu9oPLdy6G6MrPjVXwxCuhMY0CpNr4v9czbD0/wIEbLA7UHU0PYyIcsF4+ye7QVEGwhh52LuOO6IvgehvRuz/dO/pGdec310JzwzicpoyWdNycYJdKCogFKS70yWgRynifstW6PftoydzcQ03T8iyNrn7sEAvM1L6uCPLQ+FV8FkmkH/k/rf2SEhhfJ6ZMYfgBJE2zhUphc3yh1IEnY=
  template:
    metadata:
      name: pi-mix-mqtt
      namespace: iot
    type: Opaque
