---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-mqtt
  namespace: iot
spec:
  encryptedData:
    password: AgAbvIwN2xPLpz93OEbNlAyKEmAdwBTB0gMWEVAIGIFZpcdMpmtbL7ApQgEXOf9auaEVi+4rMvz2rjvY1QCuYwxX65bqxjT835RlBFvDhAxrY92oeaVkzzB5CTxbeTu1nFWTSOpez4CA7Uw857TZz5UNHx1nbn5pAv/5gXHGcBPDd3v34UUccibZzhhuvrFvdcFVfWr9UsEV9rfaxLbGr3Dato3qBiGItikjwHcgGRJCN4p+KzAVL5/bEt/wzsZ5yYAugcrl1wOHftaKZyX7GC9ouFW2HEKKowuE00q6KfG70eugsLPAt1bJMFQSelRs1deonMS5XYYQRML24lVPZvY0JdFGNfXkuSAEQNRGNKxMyIXGqxBDrlHYOxWtHXjqYTd8oNI3yG/cNX3SQlzuUEe6w+At9hh7VswRbVzTG0CMLEz8J8xdc4uzoCET6utksywa8spg4nuIqf3bOXEamh5LuyRAijrl2FsDFqZefxsJvAkzmgZU+WvCIHrnXx1GAc/o+Xx5JhVPrmRRAGeQi1qShtF7JB4aybltnHShOACsS1GvQUUEDj3rpWIQOpWxjm9R2U2qsRYT/tgG5olMey5CIJiwX+UyRSGyeDqwyajR1NuPFKzZjgQ76DZ+TTcVEtbhL3BkvE1Mmo6QSkz0uUYn/LrH2+gGv3D9L/rcoJx+kb41sPRtVpBkkPSqGvbppCvNm/x+vKO2Z45MCwdn2PyrpqDybZC1qs2qPoFjDNAmugV/2PXPptI6nWOpg02eXfsPPOBmEqsY1T74OIhGwUBv
    username: AgCFaVoe9KQrYDDxZz5/LqMLSoDX3xaE7ogLHccPEdM73dqlYkLQ5hpphPC7L5IbVOOpqVduPPvWQ/H+Mo4VbCnLdOGI1J60lp2VQVnJNkIloUgMyBgMfOuj7M5xgT0hknv0V9Q/GNF1q8nFEmGxoIfKsb/5v0A54h1jQkjgLz3LD4dSvPogGQSWq1DXN8e+uOYqxbvcXr2EEyO6NeTxyfFJPC2qqTdUyghLBi9vbjzBI28NfXDRypQNRmeSPgjZxpqwyBD+/yOPUw0m2TW3tH1jh+a8dARd0+4PA8wfTBsY12FVVS/8wy/UN3vtwLpX/+jYg9Oyf+4mleFnGHN7ha7buoH/kEwl5usvxI8lwkHUoz8K5Hh0NIuxgaVkgjRVTdAQ2h2nZoXgCWHVLOQbHswb8upEGBJ1Oj/DjAP6QSoU5RLgrOxQDuaTcjL1Avo6YitLizWxPSq5ggJSZ05VB2GvrMCWtb+HoPUaOHQvMZjLyumwJ9VVNzhFPt4B11EdZJ9ppadrxfGYmymM+tIcLq6r6qLOm4dpDstCh6V8WdRhf7IeTluHtyI6gT2+3/FqjuzxzbfspUv0nppaSlLhPkgzubphMy9+u5SU3T7bR6UFSaQtS/thQAptPVHiSOyGtdTyBccwdPh0WOEciN4vEM/GuXgxCb620uzJpgEhHUjoCuxiknObhSsGKsqSbF/4DRGqqwIz5fc=
  template:
    metadata:
      name: pi-mix-mqtt
      namespace: iot
    type: Opaque
