---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-mqtt
  namespace: iot
spec:
  encryptedData:
    password: AgCJMHvujhVbOFxlBvFiR5mob1VRWPkpRfihVJj/krU/FT0zSSdrMjGZGjnfvRmCYab/5/fOfDSVq4KbtXUHLjGxbX2oc3uZBeL8+xKa6c8uj7k/5wqzyUma3jtbwjuF1yT9U12a2630LLQrBNAOTfjYmiGlfmzKbOD49oVcTr5MTjTDUvhS0dJaUjthQRTymLMjgPc1G8wa11om5s9qPtvGtPOQWL1ItuxilQiIaA4ef03lWzCOPKr5PCGdpEzvceyJacGvosuj4DjK0AptWhYWYywo4Jl5yqGpfn94FG+euWcOrG0hY3j+TQhk8EaXLbxYXecTRoSt2f+deX5hV47inj9Q20V0Fj4ZxmMotMNg1mhfrDFfiSmG9OhmW+mFr9RvgUZJcnZa3ED0UJZ2mYortJyBpeCU98xOTRmW3rLP3fi596qA3CVI+Encs7fz7fU1LM5boX+G07i7P9rXqIy6vBifMQHMvwkj1ULRgRLFBfwCWLz224qtGMYuB0k7mhR/ghumYQ3U2DrXB6CV9WJEl3Ted+1cTMEcuXYUZ11a31YOm+btGy+KLMJCQEMlYDEFxuGTPltgkSOg2SDabCPjUpxfqi6USoj4FZ0YslV4I921sku1y5VmKSwfBQ04DTv+nKcLMeLlEC4mAN9or7X70Gs8NRCxAmzU4nPLuuoQpz1PJBo40TKNx8u99W/hyeSM98QPqul6QVv1GhXv1jomfVyNxlBB92wf6S/DWXCvsHFaCviGVTDrHZMX4rKiPibEIp1Jva6kANIHlQu4TLdl
    username: AgBHTw6ezUAYaJcQHiUv3cbItMLApX8sm8Agi01AQa98Z+Gst4EBd/OQUVWB1/fYgVDgtGQNCLKVVIkw+oz3dOZpDqjipniXeLqKG2opRg7m8x6i6QE0MMD03TIP2Uxm1H0BxVA2hRzkMnI5YHukVi5kLzDyjq/VQvjQKebRX2MF3da4PoU2TiZ+t+bYOVvZ0bLyZJp1Je2cDhdn+xTBaA+27nAja2b20UM9r45XGUm7Og3xgyWT0SfRxwZrZ76w7vId0sIsAKU385FKiNFV/c16h8uA7+eNMiKmfe7zc83d24FEjtU+HBGIPBOmx5VVAoJzRcDlnNnvqdwVF/4vIdTKxRiIKS8bHPNuCON/xPYTLE1Ti92ULBHULN6FRCBj9AhJDA4OGeNLPqDwDccH4n0MoHtBNN7MjchD3jjgaw1do/HYu5aq71jGJ7tF7cLY+RNfsMXWBdlrylVnrNGcC6Cujro3SqZ86V/zWprOL1W/XxiBx+p0rjBa+eHCElsnqoJOvYWfBxllXRcqbdCedZz5RmX2yjTDK9mZYndXicrW7TceaqBDBwYmxkLpQQGqkigFFL39Ymf6n5g/KfG3SJvyf69rlkJxVVwQs2QeuWztXX8kNPQ4cHRKRTXaH4LFaPhkoSf+N4eiGxAZv4u65EaCuaQiE35YSpyYSf2Pzp1jIgsdDLtIqSr36kVn7B0NiFkdMBLYqCs=
  template:
    metadata:
      name: pi-mix-mqtt
      namespace: iot
    type: Opaque
