---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-redis
  namespace: iot
spec:
  encryptedData:
    password: AgAgTEFU7NortAqezsZfVzSmJ0srOBNoZ6HH/LATwcU+G/ukaBHG7e0YEdhFtsufzxwD6eQEu9wmlAwSF7qbmQ+yuIo5dQ7+cIP1FlDKhOZdkCMOzq4z2rQpKudRZD8aTT+jKC9aJ7/p/QuIEJj9OfivdMdTBQut8i26FC69hmvgCmdYgHkJC+L7CWcP8I7YgxkBZYhFRhQXwPZp7eZU7Z/O8hZD+cYYWzOwoSv3qDvg9ozuHKNXcTkIBUWPBJQL8cz5jCFxDiqKLLrqEYiyjdkZPwv4pV+vgMska4oa9zxQfswqZnHyGCWKCXwVOt+cQKH4lbqcEtKO8xDIz8kxWm/qxqqTKqP/Ns5e8GjCUcKnVUs5ZnxH/47RIDfvciE/IAx0KpDkc54UfCTTy/C34TiBUJ0R6KAIwNFcWvh4vHpYnb8zSC3S8GuP57vaKUGRyJTaCZgTCsk2PIrcM8MOeWUwKVoJ1hVx7QhpA4v0+7LYeHa4IzOVFm5PVeE4ldwgLr6IC54aY9whluK68zlPdHMX5TlsTSANMrjtk7sO3+py/HM4kaYIn8YtccAZveE2hM4A1+n0miTlhBdMmnLNdiKhckljD+nOcGJRLfF5N8GOxLBbjJD6IBFg7HLfvaIsxqkudQHGDpvIPQ6pd08+OyU0svMOxzRKO2i57Yt7PCXXA8HTfJ00wwZlAnLSPRs1Hrfw9EcwgQgK5pcU2iOboWCf5q/m6ETJw1s50HdzcXwQt781wxwEO7PsRat8npKwgTBOeI2WCQVE/pWWhi2ZjMlv
    username: AgAA05KBL+aGRkzDLB5JwyBXipPkFzsWFf0Fa6YA2d4gf0pb7/wPXAekg2ugYc6ZJtvypA2lFDHZN7Z4BabRO0VxJLOU6I7rCraQdR8BYfEGqz4SukP/xRqcmnFM91kA1NLwY6sC2dMF9Dhv8eqHmKJZLSu5ppXKWJfdd4bv0qxZgVusMmmrwVczhT5VX8AkG/BIkKvsZp2fLDlJFFmPwtoWYLcV9RKdRKQEyeAoj7k2GH6nlbOwNP+a/xJnaxXn5cZiRxG1iwJBw6boPGJCNbMHNUag1OkREbHlyNUvlmb6IaFmJNILsfI5pSS6RfxIZD7nSESB78WftrfLbBxzegjkoFtGI9nljYfCduPtJnrIeobXZ49Jvm0lY8SrEMcWwc4uelMtknUNttXF+WXgksfR2FazCcafHEed+/5wo+Go+li+GJkIL77fTet3fyQFV4ccZfGujhoECHgBofIMYh7/8coTMqzIsfD4yoLYeGStIO9MK6Flj27O33F3D3fyK3qx3G+tzM2w8GyZgRzjjQoDqsq5D6wXqwe+HHlwwU87gQNsGyPAJysHv+EGfjfLhkwO5FOo7d2GvBgRv0TrnvKfIU1CEM/wVUzUUJbPX/hkBb/3O8H3fnx2QKlLf3MPq0eku964xGd9KEBj7S4KBdY7wGC1ONEkcRp7chcY1P2Nq/2jjxOfRLrvJcu+poIm61GHwnxlBkk=
  template:
    metadata:
      name: pi-mix-redis
      namespace: iot
    type: Opaque
