---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-mix-redis
  namespace: iot
spec:
  encryptedData:
    password: AgBz67aRXV5fWpqadya728oQhxJ6th12Gm7CWAsCdh+wGdzeVKeyC2FHkRGNMasGqMjhwgMzhmerlv98R5mfDLOohliS3ka3u6DMp6X0SQAUC1yu4c1mcMxkGQH3fkkefPs+Ob0f+Qug71fxPzMm4kWZhueqnvKx9GRw/PjQpWO0u2n9Nu4NYe8sgVQnVPnVSHsxtyeHcfuu/OE4pV/NJ9KKiwwUhxkOpeRiBTliIXYSafw9p0eekAWIiOnEIbiY29jLNYxwdhQwWXPpDglyVcK12gssxHvGnD9W5sy8olzBw/QE3+BM3D5OxxpLzPm0Azl2XiL3OiJHp/5VWUQxHwv8X182ieTmSUsypl/A7A17NeJRQ9MYj0nJWFofFGZ9NUcyK5Yaxy69ixJUnppEfkEMEAhJn9R4Z42nDpAylJEVs6NNbop3AXtzGid7lAl9imF/4R6wp/O4UB/bV8icKKBZDTpp2FnuKJUbmjvt0wJ4+zavt/VZu/r/D0w+lCnX77m1mBFmsJWivUwQuqy4mKPk6yszJsD5CWtcFsIOuVZKyq6m4vS88GFHGSpOWIOEcBZKZY+Nlp6A7eGIMjQdMNs5TA7xsN9FqoDyglUsLVG4gzCP0W5ebGAs/sP1GpV8R5DrcJHp9M3KO1NlO4DV2JDd96rRBgjXXdMdAAPiN7OvFDJlKeLAAJPVv6SwabzEj8ckNFE7jPli4FEd6K5M6nsdbQnsUwFr+TmK8AHw8NzHknoTAKxsQa2QlDpRSpr3cAFLh1amccp1Z5s1Hr19nDXk
    username: AgAkevzLPAiHrjwcDVicVzov5Pj/fnyJ2GUQtYu/lgxIwuXSAEDaAF+K3NuKspmx1+5MdtdeSPc13cLqYQLam0y41ax5x88CMiSQNfkXZrXAE7jc6qmUxKjE3zr2WVipZ2FxFtqqMgXz2w94KS/HFj9nlbpjkaAund06m0l95pRKcB87H474+86KSSbxOobP2mo59Z3HS51eS33TY99RHrhPo5h1q+L4M/rMkCNssNDVlDrIjN6mjlmSdnZx4ko6zwIvM8PdxbJXgsBkp/h6yfln44vzHlmN1d7PBsd41HddDYBe413GDoc+sJINB7KxDsS35+9y/MdfDhCwPRs5miLpz8VzHqbZQ0eONI3h1JImXgR1DHpeHZAMoznr5RPCf6CfcQhhdYY6c8hhKiCzMOs0Ul44ZFkeWzg4+noqdKfhbBCDI4/LCggBBMlUxRNNoQpi3LWnvwxkq4kFvC1UofAnUisno6pYPyH73YP5Ucl4PzftnNXmGZ0WRF8SnXvbROMlXw2VcFc48a5EZ8csst5j+/GKXq0aOZsSzg1m7W1HE51Bpk+9fJzQA8I84I2M3W2MJZuKNNs/hvod90uW7uIGfuvNABvG7q4q4feYf9OjOoTqvXRjSsx6Q0tWlO8RbVwGiN5GrH9aGC7N8VtUCyuTTbivpjAbnoCrlPm3BlsYp2aJOhjYVhz1m11XwSLPpoHDQvoqKGo=
  template:
    metadata:
      name: pi-mix-redis
      namespace: iot
    type: Opaque
