apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale
  namespace: iot
  labels:
    app: scale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale
  template:
    metadata:
      labels:
        app: scale
    spec:
      containers:
      - name: scale
        image: mhmdzawi/pi-mix-scale:8ef197545b79043ee876e40246cbcf71de2795e0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: MQTT_BROKER
          value: mosquitto
        - name: SCALE_MAC
          value: 50:FB:19:29:54:37
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pi-mix-mqtt
              key: password
        volumeMounts:
        - name: dbus
          mountPath: /run/dbus
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 128Mi
      volumes:
      - name: dbus
        hostPath:
          path: /run/dbus
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: the-bear
  strategy:
    type: Recreate
