apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale
  template:
    metadata:
      labels:
        app: scale
    spec:
      containers:
        - name: scale
          image: mhmdzawi/pi-mix-scale:e1f9ba16c7bfed381fe916f5239c62768c32d9f8
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: MQTT_BROKER
              value: mosquitto
            - name: SCALE_MAC
              value: "50:FB:19:29:54:37"
          volumeMounts:
            - name: dbus
              mountPath: /run/dbus
      volumes:
        - name: dbus
          hostPath:
            path: /run/dbus
