apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultrasonic
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ultrasonic
  template:
    metadata:
      labels:
        app: ultrasonic
    spec:
      containers:
        - name: ultrasonic
          image: mhmdzawi/pi-mix-ultrasonic:e1f9ba16c7bfed381fe916f5239c62768c32d9f8
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: MQTT_BROKER
              value: mosquitto
            - name: US_INTERVAL
              value: "0.5"
