---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-auth
  namespace: iot
spec:
  encryptedData:
    passwords: AgAX/iMHnKFdAiW3xVfNR92Jp09JyjzWdWAUEp8P9eB5k125OuAe1lbdDykOOG/p8WrPFnIF+h/UuexjCZec9JpC+l4dl2w7AturkHSviM+B2zsAC+dI7SUVazxqlkAgvIdA1nTQjlqGrgIbwegBoftI4FfPkmouxU2ni0boeRLEf4cHZwEklU2gggvG0d/J/fKjx1n0YKA+D6nZrNc9NynUH86fwecCUAMoLLQebDmxdDRVJgF5EYL6D74rYl27AhI3JRBq4Vh8iJuk68j1X2uLDl0UxKPa4oCSW0NnPS278gzLygIbTNV9FdkFzzDGNYeOj3EuOfZ33HP9zKNF76V8Gbm8CHJz9wdPC0CVZ6ET7cnKtoI4a89b6yAKjNKpwSorsQa0OlYcuEI0TJ3u/INiGXunVmpl5Zrr8O4vKTl8hHl1YAN8OExDWGsYm2O9uzoXfH5Y2AQrBai25bEe5nfkvFP7Vw/EcqztVOCnoKHXzfN9M0trPNlJUC/tpdO0VFOhFCyYBIr8Jg1qQnqEBsro34tf2ndpcmgH9FjwvNkP2FKAVvrXfyrygsvecObzasAQUo4eqHGErEzvCcEZDH9mTcJEnfKwIK9lbyvVKuSiX1j2/zNEX4bHrCXm9DpeIlZXWTwv/Bj/yg8MW67LUFhHEqqvbi7GL3QUpxM1KNScaFfVK6T8/3V/kh4Es9+bZYruVMYUv7I++DztBOE+e31cZY51h9Cq25lJ9hWht3NOTx6M/fbOC37NwQ+n/vN46Q7o4XaA6nsmKHlt1B5SH93luofkBsAi5Wj/B/B7/zXBkPOempjf48zGUdxgKwi0NJeJNjIR+mWuE8HWew4q5IePZ8fMR5Z18kLvMyWnKblcYaYRkc6KU/WyFrVwYfar5R+70QGvPGmbn5+CIIenphhiiULHKzOFwI18BMELvJolRrCK4YIN3X/yb70h8m/xugPu
  template:
    metadata:
      name: mosquitto-auth
      namespace: iot
    type: Opaque
