---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-auth
  namespace: iot
spec:
  encryptedData:
    passwords: AgAmVcDEUDoOFHP25vKgWdP9GlIzrf64qBigJpkhUVaG+eVAV7izRT0OjyBHcXBmQ5a8hIhQDZbpLqOHN/nFn85JhKup4/bFjbHmK1xK5LoyxAQcbZEnbgD5bP9ZUnOyshWcur+iZar8sdkGtCv0UTAf6UnSqjwUwmO+wNQ95Ox8JE0AgO+UwHnELEc5HjRwit7oElUlKgdAQ80LV/7N+7PTq9B2/MO9Bo6fyBPIowIUo59QZbA/94HJJbcc6YgbNyQiozvSGtwO3vJoviz61MduxA3NKblRsxY+bKK9pcsAurYiODEYGAw/UItz0hhgBxzIpgrSV33U/jMpS1nB4WWro++qu1f5Bx9goLwmjEm1VEvYVgvND4EvPv+fGZMty/LiklRVXBfJJndZTv3/t1t3qXuSZS7jFH/crz8TuP4v7vtG6HueY+cqSNbS/fYHRzSwYERLbE7u56JUxj8ZAqo6UuYTwTLlTX9CE5RWd3+jVOATEfGayLV34S9J8Kz3pn1E8Cgr0HyNhJw/lDz9Kg2eJ4snXZWp3A3qDUXiNJRrxa7op9zMCcFwgdwzMhBmnQ8DoKUkeF+HD2pFnHlaUOU/XkBAPSb/cUt0Q71YfA1ifxZMDTpxfjeAgaD+rhSFPPJxKf2SzZlECKH9my9lZADpjjvOoyB2HAwhIZfO1RU/txooS2hqjzlcM63lVq5q6Pp6dysqlOHjWyPTNhGWcHi7y0pRFnpy/kjhbZBu0TVwqacTGePwZKkzuBuojhy7x7IVHcg8avzt+0DobJtuOc6ElBA+7/sH0dHi3D3situ46XVS9Y57+ISqLNcOKr4uaZ3oxAlvRvpwtCkDZthsU1ASWJKnRsb9rEWGM3wTwSneR2iJ7UfcrmTM18FumZ4nRR3q3XzWb5Vt8xyXyAL4tMVdpM9Na2uqZmGEvVg4XOLyI8jgL9Ul+252knD030ciA3tG
  template:
    metadata:
      name: mosquitto-auth
      namespace: iot
    type: Opaque
