apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: iot
data:
  mosquitto.conf: 'listener 1883

    allow_anonymous false

    password_file /mosquitto/auth/passwords

    acl_file /mosquitto/config/acl

    persistence false

    max_queued_messages 150000

    max_queued_bytes 67108864

    memory_limit 134217728

    message_size_limit 4096

    log_type error

    log_type warning

    connection_messages false

    '
  acl: 'user pi-mix

    topic readwrite pi/#

    '
