apiVersion: batch/v1
kind: Job
metadata:
  name: firmware-flasher
  namespace: iot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: flasher
        image: mhmdzawi/pi-mix-firmware:010322fc7f1091c94c5f6fa3ef21df2d7181da98
        env:
        - name: BRIDGE_CONTROL_TOKEN
          valueFrom:
            secretKeyRef:
              name: bridge-control
              key: token
      nodeSelector:
        kubernetes.io/hostname: the-bear
      automountServiceAccountToken: false
    metadata:
      labels:
        app: firmware-flasher
  backoffLimit: 1
