apiVersion: batch/v1
kind: Job
metadata:
  name: firmware-flasher
  namespace: iot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: flasher
        image: mhmdzawi/pi-mix-firmware:33f0ead9b5c8d5008fda0f3cd4ae58d0fee687b3
        env:
        - name: BRIDGE_CONTROL_TOKEN
          valueFrom:
            secretKeyRef:
              name: bridge-control
              key: token
      nodeSelector:
        kubernetes.io/hostname: the-bear
      automountServiceAccountToken: false
    metadata:
      labels:
        app: firmware-flasher
  backoffLimit: 1
